name: burocracia
description: Biblioteca para manipulação de CEP, CNPJ e CPF.
version: 0.0.1
#homepage: https://www.example.com
#author: Rodrigo Muniz <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
